version: "3"
services:
    rest:
        build:
           context: ..
           dockerfile: ./dev/rest/Dockerfile
        container_name: netpen-rest
        volumes:
           - ..:/app
        ports:
           - 5000:5000
        environment:
          - FLASK_APP=./dev/rest/__main__.py
          - FLASK_ENV=development
    examples:
        image: nginx
        ports:
            - 8866:80
        volumes:
            - ../examples:/usr/share/nginx/html:ro
            - ../dev/nginx/examples:/etc/nginx/conf.d/
    demuxer:
        image: nginx
        ports:
            - 8199:80
        volumes:
            - ../dev/nginx/demuxer:/etc/nginx/conf.d/
    web:
        build:
           context: ..
           dockerfile: ./web/Dockerfile
        container_name: netpen-web
        entrypoint: /bin/sh -c "yarn install && yarn start"
        environment:
            - VITE_API_BASE=/
            - VITE_EXAMPLES_BASE=/example-files/
        volumes:
            - ../:/app
            - web_modules:/app/web/node_modules
        ports:
            - 3000:3000
volumes:
  web_modules:
networks:
    default:
        external:
            name: netpen-docker-compose-net
